---
name: 🐛 Bug Report
about: Report a reproducible bug in the current release of nautobot-data-validation-engine
---

### Environment
* Python version:  <!-- Example: 3.7.7 -->
* Nautobot version:  <!-- Example: 1.5.0 -->
* nautobot-data-validation-engine version:  <!-- Example: 2.0.0 -->

<!-- What did you expect to happen? -->
### Expected Behavior


<!-- What happened instead? -->
### Observed Behavior

<!--
    Describe in detail the exact steps that someone else can take to reproduce
    this bug using the current release.
-->
### Steps to Reproduce
1.
2.
3.
